# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Clozr' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clozr
  pod 'AFNetworking', '~> 2.5'
  pod 'BDBOAuth1Manager'
  pod 'MBProgressHUD', '~> 0.9.1'

  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'BetterSegmentedControl'
  pod 'FlatUIKit'
  pod 'OneSignal', '~> 2.0'
  pod 'DGElasticPullToRefresh’
  pod 'RAMAnimatedTabBarController', '~> 2.0.13'
  pod 'JSQMessagesViewController'
  pod 'SwiftGifOrigin', '~> 1.6.1'
  pod 'RSLoadingView', '~> 1.1'
  pod 'NVActivityIndicatorView'

  target 'ClozrTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
target 'OnesignalNotificationServiceExtension' do
    use_frameworks!

    pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
