# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Clozr' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clozr
  pod 'AFNetworking', '~> 2.5'
  pod 'BDBOAuth1Manager'
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'ICSPullToRefresh', '~> 0.6'
  pod 'CBZSplashView', '~> 1.0.0'
  pod 'SwiftyJSON'
  pod 'RegexKitLite'
  pod 'Blurry', '~> 0.0.1'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  #pod 'Firebase/Messaging'
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'BetterSegmentedControl'
  pod 'FlatUIKit'
  pod 'OneSignal', '~> 2.0'

  target 'ClozrTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  

end
target 'OnesignalNotificationServiceExtension' do
    use_frameworks!

    pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
