# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clozr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clozr
  pod 'DateTimePicker'
  pod 'AFNetworking', '~> 2.5'
  pod 'BDBOAuth1Manager'

  target 'ClozrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClozrUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
